apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitea
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://dl.gitea.io/charts
    chart: gitea
    targetRevision: 10.1.2
    helm:
      values: |
        ingress:
          enabled: true
          hosts:
            - gitea.local
        postgresql:
          enabled: true
  destination:
    server: https://kubernetes.default.svc
    namespace: gitea
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
